a2o/snoopy

- contrib/debian/changelog
- contrib/debian/rules
- doc/FILTER_exclude_spawns_of.md
- etc/snoopy.ini
- src/filter/Makefile.am
- src/filter/exclude_spawns_of.c
- src/filter/exclude_spawns_of.h
- src/filterregistry.c
The exclude_spawns_of filter lets the user specify a "black list" of programs. Snoopy will not record the execution of processes descending from one of these programs.
This is useful to limit the noise generated by predictable programs such as cron.
> Feature/filter exclude spawns of 

- contrib/debian/changelog
- contrib/debian/control
The snoopy package is available on the Ubuntu repos and should be replaced if libsnoopy is installed, especially if a new feature is configured in the snoopy.ini file.
> Add conflict rules to avoid installing both the snoopy and libsnoopy pkgs

- contrib/rhel/snoopy.spec.in
Trying to build centos rpms fails as %{buildroot}/etc already exists. Adding -p, --parents, changes the mkdir behavior to no error if existing
> added parents option to not error if the directory already exists

- lib/inih/src/ini.h
Code quality:
(not applicable for non-code fixes of course)
Commits:
Licensing:
Branching:
Permit long lines in INI file with a long message_format, otherwise the line in the log file is truncated.
> Permit long lines in INI file.

- config.h.in
- src/datasource/cmdline.c
Code quality:
(not applicable for non-code fixes of course)
Commits:
Licensing:
Branching:
This commit makes snoopy compile, but someone must confirm that the functionality is the same.
The error messages I get before this commit are:
```
CC       cmdline.lo
cmdline.c: In function ‘snoopy_datasource_cmdline’:
cmdline.c:71:79: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
^~
cmdline.c:71:30: note: did you mean to dereference the pointer?
for (cmdLineArgCount=0 ; …
```
> Make snoopy compile on 64-bit Arch Linux with GCC 7.1.1

- tests/datasource/datasource_login.sh
Code quality:
(not applicable for non-code fixes of course)
Commits:
Licensing:
Branching:
Playing with snoopy in a dev docker container I hit an error with the "datasource_login" test beause whilst `tty` returned a valid tty, no login name existed for `logname` to return.
This PR just makes it so that if the test considers `logname` to be the source of truth, it does so consistently rather than assuming a correlation with `tty`, increasing the stability of tests in containers with unusual login/tty properties.
> Fix datasource_login test to more consistenly use `logname`

- ChangeLog
- configure.ac
This PR is a substitute for #160:
- It cherry-picks usable commit from #160 
- Additionally, it expands the scope to allow backslashes to be specified on the `./configure --with-message-format="X"` line as well.
> GH-160 double quotes in default message

- ChangeLog
- config.h.in
- configure.ac
- etc/snoopy.ini.in
- src/datasource/Makefile.am
- src/datasource/snoopy_configure_command.c
- src/datasource/snoopy_configure_command.h
- src/datasourceregistry.c
- tests/datasource/Makefile.am
- tests/datasource/datasource_snoopy_configure_command.sh
> GH #113: Store ./configure command used during the build and make it accessible via a new data source

- configure.ac
- configure.scan
- lib/inih/patches/0002-prefix-function-names.diff
- lib/inih/src/ini.h
- lib/liblcthw/patches/0004-prefix-function-names.diff
- lib/liblcthw/src/list.h
- src/datasource/rpname.c
- src/filter/exclude_spawns_of.c
- tests/Makefile.am
- tests/general/Makefile.am
- tests/general/_bootstrap.sh
- tests/general/general-symbol-leaks.sh
Fixes #119.
Symbols that were defined by the external ini parsing library (namely `ini_parse()` function) is interfering with PHP's function of the same name. Weirdly enough, the issue only happens when PHP is running under Apache (as mod_php), and not in the standalone more.
The solution is to stop the symbol leak, and use `snoopy_` prefix  for all the symbols that the library makes available.
There are a few places where symbols are leaking and need fixing:
- `lib/inih/`
- `lib/liblcthw/`
- `src/datasource/rpname.c`
- `src/filter/exclude_spawns_of.c`
Lastly, create a test that will always check the library for leaked symbols.
> GH #119: Fix symbol leaks

- src/filter/exclude_spawns_of.c
- tests/filter/Makefile.am
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-first.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-last.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-mid.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-singlearg.sh
- tests/filter/filter_exclude_spawns_of-mustlog-multiarg.sh
- tests/filter/filter_exclude_spawns_of-mustlog-singlearg.sh
Code quality:
(not applicable for non-code fixes of course)
Commits:
Licensing:
Branching:
This PR fixes issue #117 by parsing /proc/<pid>/stat more robustly. The technique is based on the one used by ps (see http://sources.debian.net/src/procps/2:3.3.9-9/proc/readproc.c/#L502), which accounts for the possibility of spaces and parens in command names.
> Improve parsing in exclude_spawns_of filter

- tests/bin/Makefile.am
- tests/bin/spaceparent.c
- tests/filter/Makefile.am
- tests/filter/filter_exclude_spawns_of-mustdrop-spaceparent.sh
- tests/filter/filter_exclude_spawns_of-mustlog-spaceparent.sh
> GH #117: Add tests for exclude_spawns_of that verify if parent processes with spaces in their name are correctly detected

- src/filter/exclude_spawns_of.c
The implementation of exclude_spawns_of somewhat predates widespread usage of
Linux containers. Before containers, PID 1 was always some sort of an init
process, always there, always called `init`, and it somewhat made sense to
just ignore it.
But with the onset of containers/namespaces, the PID 1 inside an i.e. Docker
container can be any executable that is configured as container's entrypoint.
The solution is to adjust the filter's method and it perform the process name
analysis all the way up to and including PID 1, whatever that process may be.
> GH #145: Enable analysis of PID 1 in filter `exclude_spawns_of`

- src/datasource/cmdline.c
(Not really possible to achieve during regular operation, just during test suite runs.)
> bugfix: Fix invalid memory access in cmdline datasource when argv[] is empty

- .github/workflows/build-qa-os-matrix-large.yml
- .github/workflows/install-qa-os-matrix.yml
- dev-tools/install-dev-software.sh
- install/install-snoopy.sh
The objective is to have changes to install script and newly released stable versions verified automatically on all "supported" OSes
> install+ci: Add "proper" multi-OS support to install script + verification workflow

- src/datasource/domain.c
According to /etc/hosts' manpage, comments that don't start at the beginning of
a line should be allowed, but the `hostname` command (at least on Ubuntu 20.04),
or more likely the underlying `getaddrinfo()` function, doesn't actually return
the domain name in that case. Regardless, let's do the right thing here and
extract the domain name successfully anyway.
> core/ds/domain: Fix incorrect handling of comments in /etc/hosts

- src/datasource/cmdline.c
- src/snoopy.h
> datasource/cmdline: Fix incorrect max string length determination

- src/datasource/cmdline.c
- [X ] My submission does one logical thing only (one bugfix, one new feature). If I will want to supply multiple logical changes, I will submit multiple pull requests.
- [X ] I have read and understood the [CONTRIBUTING guide](https://github.com/a2o/snoopy/blob/master/.github/CONTRIBUTING.md)
Code quality:
(not applicable for non-code fixes)
Commits:
- [X ] My commits are logical, easily readable, and with concise comments.
- [X ] My commits follow the KISS principle: do one thing, and do it well.
Licensing:
- [X ] I am the author of this submission or I have been authorized by the submission copyright holder to issue this pull request. By issuing this pull request the copyright holder agrees that their …
> Fix cmdline datasource overflow

- dev-tools/install-dev-software.sh
- install/install-snoopy.sh
Latest Tumbleweed does not include the `find` utility like it used to.
> install: Fix OpenSUSE installer (install `findutils` package if needed)

- .github/workflows/build-qa-config-matrix-large.yml
- .github/workflows/build-qa-config-matrix-small.yml
- .github/workflows/build-qa-os-matrix-large.yml
- .github/workflows/build-qa-os-matrix-small.yml
- .github/workflows/build-qa-out-of-tree-build.yml
- .github/workflows/build-qa-verify-make-targets-prefix.yml
- .github/workflows/code-qa-autoreconf.yml
- .github/workflows/code-qa-autoscan.yml
- .github/workflows/code-qa-codeql.yml
- .github/workflows/code-qa-coverity.yml
- .github/workflows/code-qa-sonarcloud.yml
- .github/workflows/code-qa-valgrind.yml
- .github/workflows/install-qa-installfile.yml
- .github/workflows/install-qa-os-matrix.yml
- .github/workflows/install-qa-readme.yml
- .github/workflows/release-qa-os-matrix-install-from-source.yml
- dev-tools/install-dev-software.sh
- install/install-snoopy.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-first.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-last.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-multiarg-mid.sh
- tests/filter/filter_exclude_spawns_of-mustdrop-singlearg.sh
Done:
- Replace CentOS 7 & 8 with AlmaLinux 8 & 9,
- Introduce CentOS stream8 & stream9
- Deprecate Debian stretch
- Deprecate openSuse Leap 15.2 & introduce openSUSE Leap 15.4
- Introduce Ubuntu 22.04
> ci/cd: Refresh/update images used for testing

- lib/liblcthw/patches/0005-fix-sq-code-smells.diff
- lib/liblcthw/src/list.c
The macro in question is expanded into `if(...){...}`, thus suffixing the macro
statement with a semicolon creates and empty statement (between `}` and `;`).
SQ/SC references:
- https://sonarcloud.io/project/issues?issues=AXjNfUfBZ-ncPEFTe1Ib&open=AXjNfUfBZ-ncPEFTe1Ib&id=snoopy
- https://sonarcloud.io/project/issues?issues=AXjNfUfBZ-ncPEFTe1Ic&open=AXjNfUfBZ-ncPEFTe1Ic&id=snoopy
- https://sonarcloud.io/project/issues?issues=AXjNfUfBZ-ncPEFTe1Id&open=AXjNfUfBZ-ncPEFTe1Id&id=snoopy
- https://sonarcloud.io/project/issues?issues=AXjNfUfBZ-ncPEFTe1Ie&open=AXjNfUfBZ-ncPEFTe1Ie&id=snoopy
> ext/list: Fix the last remaining code smell(s)

- ChangeLog
- configure.ac
There have been a few reports of odd segmentation fault issues
circulating around the internet such as this one:
https://bugs.launchpad.net/ubuntu/+source/snoopy/+bug/1698090
Let's enable thread safety (which has already solved a few occurences
of similar issues) and make these a thing of a past (or resolve the actual
issue once threading-related errors are out of the picture).
> Enable thread safety by default

- etc/snoopy.ini.in
- src/action/log-syscall-exec.c
- src/message.c
- src/message.h
- src/output/devlogoutput.c
- src/output/fileoutput.c
- src/output/syslogoutput.c
- tests/bin/action-run-everything.c
- tests/bin/action-run-messageformat.c
- tests/output/Makefile.am
- tests/output/output_file-dynamic.sh
(i.e. `/var/log/snoopy.log-%{datetime:%Y-%m-%d}`)
(Fixes GitHub issue #229.)
> core: Add support for dynamic output file paths 

- .github/workflows/build-qa-config-matrix-large.yml
- .github/workflows/build-qa-config-matrix-small.yml
- .github/workflows/build-qa-os-matrix-large.yml
- .github/workflows/build-qa-os-matrix-small.yml
- .github/workflows/build-qa-out-of-tree-build.yml
- .github/workflows/build-qa-verify-make-targets-prefix.yml
- .github/workflows/code-qa-codeql.yml
- .github/workflows/code-qa-coverity.yml
- .github/workflows/code-qa-sonarcloud.yml
- .github/workflows/code-qa-valgrind.yml
GNU suggests this option should not be enabled by default, since identical
options are passed into subdirectories containing `configure` scripts (i.e.
if someone is importing Snoopy into their main project and building it in
the main project's subdirectory).
(That said, I wanted to enable this option for everybody regardless of the
suggestion above, but I could not find a way to do it.)
> ci: Error out if an unknown `./configure` option is encountered

- .gitignore
- packaging/deb/extra-files/snapd-apparmor-profile
- packaging/deb/rules
We're only adding this to a packaged Snoopy version (Ubuntu only for now),
and not to stock .tar.gz distribution, since this is a distribution-related
matter.
Related to issue #237.
> packaging/ubuntu: Add AppArmor profile adjustment for snapd

- .github/workflows/build-qa-arch-matrix.yml
- tests/bin/action-stress-threads.c
- tests/bin/action-stress-threadsexec.c
(i.e. in 32-bit Debian Sid container)
> tests/bin/threads: Fix non-explicit casting that caused non-64bit builds to fail 

- .github/workflows/code-qa-sonarcloud.yml
- dev-tools/submit-to-sonarcloud.sh
Code quality:
(not applicable for non-code fixes)
Commits:
Licensing:
Branching:
SonarCloud now has an automatic analysis caching which gets saved on the server. See https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache.
> Enable SonarCloud analysis cache

- configure.scan
- src/output/socketoutput.c
Code quality:
(not applicable for non-code fixes)
Commits:
Licensing:
Branching:
On older gcc we can get a stringop-overflow warning, since it trying to predict a nonstring overflow. It could be fixed with strnlen() function.
> Use strnlen instead of strlen

- src/configfile.c
- tests/output/Makefile.am
- tests/output/output_file-dynamic-arg.sh
> output/file: Fix datasource argument handling in output specification

- dev-tools/install-dev-software.sh
- install/install-snoopy.sh
CI stopped working for Tumbleweed (their rolling release version) because it was missing `awk` all of the sudden.
> install/dev-tools: Add `awk` to OpenSUSE installer(s)

- .github/workflows/packaging-qa-os-matrix-large.yml
- .github/workflows/packaging-qa-os-matrix-small.yml
- .github/workflows/publish-native-packages.yml
- .github/workflows/release-qa-os-matrix-install-from-repo.yml
Packaging-related Actions for Arch Linux started failing because the whole process gets stuck on a hanged `fakeroot` process. This seems to be the relevant issue: https://github.com/docker/for-mac/issues/7331
Disabling Arch Linux packaging support until this issue is resolved.
> ci/packaging: Disable Arch Linux-related packaging Actions
